### ISSUE TITLE
Support for `6/2(1+2)` expression 

### ISSUE THREAD

**Issue by NhanAZ** [Muqsit/arithmexp#14]
`6/2(1+2)`
i think this expression should be parsed as `6/[2(1+2)]` instead of throwing an error.

\* *Sorry I couldn't find a suitable title for this issue*

###### > https://youtu.be/URcUvFIUIhQ (may be related)

**Comment by Muqsit** [comment]
With much of this project being heavily dependent on PHP's expression syntax, allowing implicit multiplication like above would raise confusion and lead to probable bugs due to a missing operator being replaced by `*`.
