### ISSUE TITLE
Improve sub-expression comparison in Operator Strength Reduction

### ISSUE THREAD

**Issue by Muqsit** [Muqsit/arithmexp#8]
Operator Strength Reduction's implementation is too straightforward at the moment. As it does a mere `leftTokens == rightTokens` comparison for division, multiplication and subtraction, [`(x * y) - (x * y)` translates to a `ConstantExpression(0)`](https://arithmexp.pages.dev/#(x%20*%20y)%20-%20(x%20*%20y)) while [`(x * y) - (y * x)` stays the same](https://arithmexp.pages.dev/#(x%20*%20y)%20-%20(y%20*%20x)).
![image](https://user-images.githubusercontent.com/15074389/194297653-e69634ec-246d-4447-a42f-7b6cb41574cd.png)

**Comment by sylvrs** [comment]
For an initial step, perhaps adding something like `isCommutative` for `BinaryOperator` would be useful. From there, it'd be a bit of logic to check the expression for their ability to be commutative.
